# Changes here will be overwritten by Copier
_commit: v0.4.2
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2026'
email: dschristianson@lbl.gov
full_name: D.S. Christianson
gh_action_docs_preview: true
gh_action_pypi: true
github_org: dschristianson
license: MIT
project_description: This is the project description.
project_name: basin3dschema
project_slug: basin3dschema

